name: Terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
permissions:
  issues: write
  pull-requests: write
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.6

    - name: Terraform Init
      id: init
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      id: plan
      working-directory: terraform
      run: terraform plan -no-color

    - name: Terraform apply
      id: apply
      working-directory: terraform
      run: terraform apply --auto-approve